<a href="https://colab.research.google.com/github/Asmina-hub/LLM-from-scratch/blob/main/embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Token Embdedding with embedding layer

In [5]:
import torch
import torch.nn as nn
import tiktoken

In [26]:
text1="My name is Asmina Nassar"
text2= "i am awsome"
text = "<|endoftext|>".join([text1,text2])

tokenizer= tiktoken.get_encoding('gpt2')
encoded_id= torch.tensor(tokenizer.encode(text, allowed_special={"<|endoftext|>"}))
print(encoded_id)

tensor([ 3666,  1438,   318,  1081,  1084,    64, 38742,   283, 50256,    72,
          716,  3253, 11246])


In [29]:
vocabulary_size = tokenizer.n_vocab
output_dim = 5

In [30]:
embedding=nn.Embedding(vocabulary_size,output_dim)

In [34]:
text_test = "Asmina is awsome"
tokenizer_new= tiktoken.get_encoding('gpt2')

encoded_id_new=torch.tensor(tokenizer_new.encode(text_test,disallowed_special=()))
print(encoded_id_new)
embedding(encoded_id_new)

tensor([ 1722,  1084,    64,   318,  3253, 11246])


tensor([[ 1.1521,  0.3402, -0.8716, -0.5417,  0.1836],
        [-0.7131,  0.0549,  0.4634, -1.1421,  0.7884],
        [ 1.4089, -0.3232,  0.3339,  0.4120, -0.4822],
        [-0.4287,  0.1926, -0.0466,  1.5651, -0.6425],
        [-0.5428,  0.8862,  0.4489, -0.3679,  0.6931],
        [-0.9884,  0.1718,  0.3104, -2.0498, -1.3629]],
       grad_fn=<EmbeddingBackward0>)